# Generated by Django 5.2.7 on 2025-10-29 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('share_now', models.BooleanField(blank=True, default=None, null=True)),
                ('share_at', models.DateTimeField(blank=True, null=True)),
                ('share_start_at', models.DateTimeField(blank=True, null=True)),
                ('share_complete_at', models.DateTimeField(blank=True, null=True)),
                ('share_on_linkedin', models.BooleanField(default=False)),
                ('shared_at_linkedin', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
